# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f18d8610b1c7000154b58d684ea19ba504476d3187f6594c65c3be5659665740ead7d115db8baa839a9d619a98837c08f6eefdc04bb89ad7bbc5522797f43729

test:
  secret_key_base: 1adca66100257ea6c48fa03306bf929f35280a1015fa256543ee932cdb07418b9c73404b5f85820e8770b5be48856723850f964ef97ab94bb2b2dd5bd140417f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
